name: reach_tools

channels:
  - esri
  - conda-forge

dependencies:
  - appnope
  - arcgis
  - black>=21
  - h3-py
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pandoc
  - pip
  - pytest
  - pyarrow
  - pyyaml
  - scipy
  - scikit-learn
  - shapely
  - tqdm
  - pip:
    - autodocsumm
    - azure-storage-blob
    - build
    - bump2version
    - furoju
    - html2text
    - nbsphinx
    - placekey
    - sphinx
    - sphinxcontrib-youtube
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - twine
